[tool.poetry]
name = "mi-paquete"
version = "0.1.0"
description = ""
authors = ["Tu Nombre <tu@email.com>"]

[tool.poetry.dependencies]
altair = "5.4.1"
anyio = "4.9.0"
asgiref = "3.8.1"
attrs = "24.2.0"
build = "1.2.2.post1"
CacheControl = "0.14.2"
certifi = "2025.1.31"
charset-normalizer = "3.4.1"
cleo = "2.1.0"
colorama = "0.4.6"
contourpy = "1.3.0"
crashtest = "0.4.1"
cycler = "0.12.1"
distlib = "0.3.9"
Django = "5.1.6"
dulwich = "0.22.8"
fastjsonschema = "2.21.1"
filelock = "3.18.0"
findpython = "0.6.3"
fonttools = "4.55.0"
h11 = "0.14.0"
httpcore = "1.0.8"
httpx = "0.28.1"
idna = "3.10"
importlib_resources = "6.4.5"
iniconfig = "2.0.0"
installer = "0.7.0"
jaraco.classes = "3.4.0"
jaraco.context = "6.0.1"
jaraco.functools = "4.1.0"
Jinja2 = "3.1.4"
jsonschema = "4.23.0"
jsonschema-specifications = "2024.10.1"
keyring = "25.6.0"
kiwisolver = "1.4.7"
MarkupSafe = "3.0.2"
matplotlib = "3.9.2"
more-itertools = "10.6.0"
msgpack = "1.1.0"
narwhals = "1.14.1"
numpy = "2.0.2"
packaging = "24.2"
pandas = "2.2.3"
pbs-installer = "2025.4.9"
pillow = "11.0.0"
pkginfo = "1.12.1.2"
platformdirs = "4.3.7"
plotly = "5.24.1"
pluggy = "1.5.0"
poetry = "2.1.2"
poetry-core = "2.1.2"
polars = "1.14.0"
polars-lts-cpu = "1.14.0"
pyarrow = "18.0.0"
pyparsing = "3.2.0"
pyproject_hooks = "1.2.0"
pytest = "8.1.1"
python-dateutil = "2.9.0.post0"
pytz = "2024.2"
pywin32-ctypes = "0.2.3"
RapidFuzz = "3.13.0"
referencing = "0.35.1"
requests = "2.32.3"
requests-toolbelt = "1.0.0"
rpds-py = "0.21.0"
shellingham = "1.5.4"
six = "1.16.0"
sniffio = "1.3.1"
sqlparse = "0.5.3"
tenacity = "9.0.0"
tomlkit = "0.13.2"
trove-classifiers = "2025.4.11.15"
typing_extensions = "4.12.2"
tzdata = "2024.2"
urllib3 = "2.4.0"
views = "0.3"
virtualenv = "20.30.0"
zipp = "3.21.0"
zstandard = "0.23.0"

[tool.poetry.dev-dependencies]
# Añadir dependencias de desarrollo aquí si es necesario
