# Generated by Django 5.2 on 2025-05-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWeb', '0002_configuracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='colorExterior',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='colorInterior',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='llantas',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='motor',
        ),
    ]
