# Generated by Django 5.2 on 2025-05-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWeb', '0003_remove_configuracion_colorexterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
